// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcPxVKvG3cNIZkgYHEDqKUIMUQv9BKug',
    appId: '1:597570191944:web:21d4ddc1e91d6cb2e50e7d',
    messagingSenderId: '597570191944',
    projectId: 'tapinacozzetta',
    authDomain: 'tapinacozzetta.firebaseapp.com',
    storageBucket: 'tapinacozzetta.firebasestorage.app',
    measurementId: 'G-PXQ9MCEVNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd4AATAhwEBorhN2sWcqgK8VGL86IZcAI',
    appId: '1:597570191944:android:22559745cf35f74de50e7d',
    messagingSenderId: '597570191944',
    projectId: 'tapinacozzetta',
    storageBucket: 'tapinacozzetta.firebasestorage.app',
    databaseURL:  'https://tapinacozzetta-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx4QiFVBBpq3MIEW4q_eXDiHjt0ZGdKTU',
    appId: '1:597570191944:ios:1c91c09340369694e50e7d',
    messagingSenderId: '597570191944',
    projectId: 'tapinacozzetta',
    storageBucket: 'tapinacozzetta.firebasestorage.app',
    iosBundleId: 'com.example.compassWebApp',
    databaseURL:  'https://tapinacozzetta-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx4QiFVBBpq3MIEW4q_eXDiHjt0ZGdKTU',
    appId: '1:597570191944:ios:1c91c09340369694e50e7d',
    messagingSenderId: '597570191944',
    projectId: 'tapinacozzetta',
    storageBucket: 'tapinacozzetta.firebasestorage.app',
    iosBundleId: 'com.example.compassWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbcPxVKvG3cNIZkgYHEDqKUIMUQv9BKug',
    appId: '1:597570191944:web:91efece8cd408879e50e7d',
    messagingSenderId: '597570191944',
    projectId: 'tapinacozzetta',
    authDomain: 'tapinacozzetta.firebaseapp.com',
    storageBucket: 'tapinacozzetta.firebasestorage.app',
    measurementId: 'G-0H6DL4E465',
  );
}
